---
- job:
    parent: tox-py39
    name: tox-py39-gnpy
    required-projects:
      - name: github.com/vexxhost/zuul-base-jobs
        override-checkout: main

- project:
    check:
      jobs:
        - tox-py39-gnpy
