
FROM python:3.6

#COPY . /app

#RUN pip install -r /app/requirements.txt

#ENV PYTHONPATH=/app

#WORKDIR /app/examples

ARG BRANCH="develop"

#ADD https://github.com/Telecominfraproject/oopt-gnpy/archive/${BRANCH}.zip /tmp

#RUN unzip /tmp/develop.zip -d /

RUN git clone --single-branch --branch ${BRANCH} https://github.com/Telecominfraproject/oopt-gnpy.git

RUN pip install -r /oopt-gnpy/requirements.txt

ENV PYTHONPATH=/oopt-gnpy

WORKDIR /oopt-gnpy/examples

ADD run.sh ./run.sh

#RUN groupadd -g 999 gn && \
#    useradd -r -u 999 -g gn gn
#RUN chown -R gn:gn ../
RUN chmod -R 777 ../

#USER gn

ENTRYPOINT [""]

